version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
  
  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      FTP_USER_NAME: user
      FTP_USER_PASS: password
      FTP_USER_HOME: /home/ftpusers/user
    volumes:
      - ./ftp-data:/home/ftpusers/user
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
