services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./channels:/code/channels
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
  
  ftp:
      container_name: ftp-server
      image: garethflowers/ftp-server
      environment:
        - FTP_USER=user
        - FTP_PASS=pass
      restart: always
      ports:
        - '20-21:20-21/tcp'
        - '40000-40009:40000-40009/tcp'   # passive mode
      volumes:
          - ./channels:/home/user/channels

networks:
  app-network:
    driver: bridge
