services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"

    env_file:
      - .env
    volumes:
      - ./channels:/code/channels
      - ./database:/code/database
      - ./logs:/code/logs
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:8080"
  
  ftp:
      container_name: ftp-server
      image: garethflowers/ftp-server
      environment:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
      restart: always
      ports:
        - '20-21:20-21/tcp'
        - '40000-40009:40000-40009/tcp'   # passive mode
      volumes:
          - ./channels:/home/user/channels

networks:
  app-network:
    driver: bridge
